name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install pytest
      - run: python -m pip install pytest
      - name: Running pytest
      - run: python -m pytest -v
