name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: python3 -m pip install pytest
      - run: python3 -m pytest -v
