name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: python3 -m pip install poetry
      - run: python3 -m poetry install
      - run: python3 -m pytest -v
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3

